### ISSUE TITLE
query wrt maven file entry for phantomjs

### ISSUE THREAD

**Issue by vikramvi** [Sild/webtest#1]
Hi,

Can you please clarify why you have entries for phantomjs in pom.xml and still have downloaded the driver under resources folder ?

Thanks & Regards,
Vikram

**Comment by Sild** [comment]
The maven dependency is just a driver to control the external application (which provide by phantomjs binary).
So we need them together: 
maven phantomjs driver answer the question HOW we will control
binary phantomjs answer the question WHAT we will controll

Thanks

**Comment by vikramvi** [comment]
Hi Sild,

Thanks for clarification.

Regards,
Vikram
